### ISSUE TITLE
Result paging

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-engine-web#309]
support for result paging, .e.g 4 pages maybe?

**Comment by khou** [comment]
raised priority for demo needs

thinking about using http://esimakin.github.io/twbs-pagination/ to handle UI
currently, limit 1000 will kill the DOM on Chrome and require a refresh to continue use. The same problem as #24 
However, other browsers are fine so this is a javascript issue. Will track this specifically on #24

**Comment by khou** [comment]
#338
