### ISSUE TITLE
initial load of engine-web is very slow on EBS

### ISSUE THREAD

**Issue by khou** [dashbase/dashbase-engine-web#321]
dashbase engine web appears to take a very long time to load, however it is the engine taking a long time to produce a response. This behavior seems to only be replicable on an AWS EC2 instance, and is noticeable starting from just 80M documents. Perhaps it is something to do with AWS EBS storage drives?  @zengmin2016

**Comment by khou** [comment]
further research shows that the difference is about 1000x, and response becomes great again after letting it load or a refresh.

**Comment by javasoze** [comment]
this smells like ebs being slow warming up and it is a concern...

some info:
http://www.slideshare.net/AmazonWebServices/stg302-28617072

**Comment by javasoze** [comment]
This is a backend issue with EBS:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSPerformance.html
https://www.youtube.com/watch?v=2wKgha8CZ_w
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-io-characteristics.html

**Comment by khou** [comment]
We'll try to keep the EBS disk warm by this #336
