### ISSUE TITLE
sql search: am/pm error, time 12:00:00 is parsed to 00:00:00

### ISSUE THREAD

**Issue by ZongqiangZhang** [dashbase/dashbase-engine-web#327]
In sql search panel, search any keyword with time range. e.g. SELECT * where query is "error" after '2016-12-21 12:00:00' before '2016-12-21 14:00:00'.
The searched result is from '2016-12-21 00:00:00' instead of '2016-12-21 12:00:00'.

**Comment by javasoze** [comment]
@ZongqiangZhang Please download the latest code drop and verify. Thanks!

**Comment by ZongqiangZhang** [comment]
verify done. time parser is right using 2017-01-09 18:53:30 UTC build
