### ISSUE TITLE
Display field names in UI with proper casing

### ISSUE THREAD

**Issue by alexmunk** [dashbase/dashbase-engine-web#332]
The UI shows field names all caps. i.e. HOST. But Dashbase only knows what to do if they are cased properly. host, bytesSent, etc. This is bad.

Please display the fields in the UI as the user must type them when searching.

**Comment by javasoze** [comment]
I think the problem is with style.css:

.dashboard #dashboard-results .hit-field
{
	color:#A5A7AA;
	display:block;
	font-size:.8em;
	font-weight:700;
	text-transform:uppercase;
}

Maybe remove the text-transform?
